# Generated by Django 5.1.2 on 2024-11-30 12:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveIntegerField(validators=[api.models.validate_year_not_in_future]),
        ),
    ]
